// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v4.25.1
// source: driftnode.proto

package driftnodepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Empty carries no parameters. Used by RPCs that need no input.
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_driftnode_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_driftnode_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_driftnode_proto_rawDescGZIP(), []int{0}
}

// EmptyResp acknowledges a command with a status string.
type EmptyResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyResp) Reset() {
	*x = EmptyResp{}
	mi := &file_driftnode_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyResp) ProtoMessage() {}

func (x *EmptyResp) ProtoReflect() protoreflect.Message {
	mi := &file_driftnode_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyResp.ProtoReflect.Descriptor instead.
func (*EmptyResp) Descriptor() ([]byte, []int) {
	return file_driftnode_proto_rawDescGZIP(), []int{1}
}

func (x *EmptyResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// WhoamiResp is the node's own identity and optional profile fields projected
// from the own logs.
type WhoamiResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Stable        bool                   `protobuf:"varint,3,opt,name=stable,proto3" json:"stable,omitempty"`
	DisplayName   string                 `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	HasAvatar     bool                   `protobuf:"varint,5,opt,name=has_avatar,json=hasAvatar,proto3" json:"has_avatar,omitempty"`
	Bio           string                 `protobuf:"bytes,6,opt,name=bio,proto3" json:"bio,omitempty"`
	FirstName     string                 `protobuf:"bytes,7,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,8,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Location      string                 `protobuf:"bytes,9,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhoamiResp) Reset() {
	*x = WhoamiResp{}
	mi := &file_driftnode_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhoamiResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoamiResp) ProtoMessage() {}

func (x *WhoamiResp) ProtoReflect() protoreflect.Message {
	mi := &file_driftnode_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhoamiResp.ProtoReflect.Descriptor instead.
func (*WhoamiResp) Descriptor() ([]byte, []int) {
	return file_driftnode_proto_rawDescGZIP(), []int{2}
}

func (x *WhoamiResp) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *WhoamiResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *WhoamiResp) GetStable() bool {
	if x != nil {
		return x.Stable
	}
	return false
}

func (x *WhoamiResp) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *WhoamiResp) GetHasAvatar() bool {
	if x != nil {
		return x.HasAvatar
	}
	return false
}

func (x *WhoamiResp) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *WhoamiResp) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *WhoamiResp) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *WhoamiResp) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

// IdentityReq targets one driftnode identity.
type IdentityReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityReq) Reset() {
	*x = IdentityReq{}
	mi := &file_driftnode_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityReq) ProtoMessage() {}

func (x *IdentityReq) ProtoReflect() protoreflect.Message {
	mi := &file_driftnode_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityReq.ProtoReflect.Descriptor instead.
func (*IdentityReq) Descriptor() ([]byte, []int) {
	return file_driftnode_proto_rawDescGZIP(), []int{3}
}

func (x *IdentityReq) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

// VerifyResp reports the identity that was verified or unverified.
type VerifyResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyResp) Reset() {
	*x = VerifyResp{}
	mi := &file_driftnode_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyResp) ProtoMessage() {}

func (x *VerifyResp) ProtoReflect() protoreflect.Message {
	mi := &file_driftnode_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyResp.ProtoReflect.Descriptor instead.
func (*VerifyResp) Descriptor() ([]byte, []int) {
	return file_driftnode_proto_rawDescGZIP(), []int{4}
}

func (x *VerifyResp) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

// FeedItem is one post in the merged timeline.
type FeedItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Author        string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Text          string                 `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	LikeCount     int32                  `protobuf:"varint,6,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	Likers        []string               `protobuf:"bytes,7,rep,name=likers,proto3" json:"likers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedItem) Reset() {
	*x = FeedItem{}
	mi := &file_driftnode_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedItem) ProtoMessage() {}

func (x *FeedItem) ProtoReflect() protoreflect.Message {
	mi := &file_driftnode_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedItem.ProtoReflect.Descriptor instead.
func (*FeedItem) Descriptor() ([]byte, []int) {
	return file_driftnode_proto_rawDescGZIP(), []int{5}
}

func (x *FeedItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FeedItem) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *FeedItem) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *FeedItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FeedItem) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *FeedItem) GetLikeCount() int32 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *FeedItem) GetLikers() []string {
	if x != nil {
		return x.Likers
	}
	return nil
}

// FeedPageReq returns a page of the merged timeline, newest-first. page is
// the 0-indexed page number (page 0 is the snapshot the subscribe stream
// sends). The page size is fixed server-side. mine filters to the user's own
// posts. all_likes triggers an on-demand like fetch from connected zens for
// the user's own posts in the returned page.
type FeedPageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Mine          bool                   `protobuf:"varint,2,opt,name=mine,proto3" json:"mine,omitempty"`
	AllLikes      bool                   `protobuf:"varint,3,opt,name=all_likes,json=allLikes,proto3" json:"all_likes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedPageReq) Reset() {
	*x = FeedPageReq{}
	mi := &file_driftnode_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedPageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedPageReq) ProtoMessage() {}

func (x *FeedPageReq) ProtoReflect() protoreflect.Message {
	mi := &file_driftnode_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedPageReq.ProtoReflect.Descriptor instead.
func (*FeedPageReq) Descriptor() ([]byte, []int) {
	return file_driftnode_proto_rawDescGZIP(), []int{6}
}

func (x *FeedPageReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FeedPageReq) GetMine() bool {
	if x != nil {
		return x.Mine
	}
	return false
}

func (x *FeedPageReq) GetAllLikes() bool {
	if x != nil {
		return x.AllLikes
	}
	return false
}

// FeedPageResp is one page of merged-timeline posts, newest-first, with a
// has_more flag indicating older posts remain.
type FeedPageResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*FeedItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedPageResp) Reset() {
	*x = FeedPageResp{}
	mi := &file_driftnode_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedPageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedPageResp) ProtoMessage() {}

func (x *FeedPageResp) ProtoReflect() protoreflect.Message {
	mi := &file_driftnode_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedPageResp.ProtoReflect.Descriptor instead.
func (*FeedPageResp) Descriptor() ([]byte, []int) {
	return file_driftnode_proto_rawDescGZIP(), []int{7}
}

func (x *FeedPageResp) GetItems() []*FeedItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *FeedPageResp) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

// PostReq creates a post. Passphrase unlocks the signing key; omit when the
// daemon is already unlocked. ParentId, when non-empty, is the event ID of the
// post being replied to; a reply is a post with a parent.
type PostReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Passphrase    string                 `protobuf:"bytes,2,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	ParentId      string                 `protobuf:"bytes,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostReq) Reset() {
	*x = PostReq{}
	mi := &file_driftnode_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostReq) ProtoMessage() {}

func (x *PostReq) ProtoReflect() protoreflect.Message {
	mi := &file_driftnode_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostReq.ProtoReflect.Descriptor instead.
func (*PostReq) Descriptor() ([]byte, []int) {
	return file_driftnode_proto_rawDescGZIP(), []int{8}
}

func (x *PostReq) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *PostReq) GetPassphrase() string {
	if x != nil {
		return x.Passphrase
	}
	return ""
}

func (x *PostReq) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

// PostResp reports the created event id.
type PostResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostResp) Reset() {
	*x = PostResp{}
	mi := &file_driftnode_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostResp) ProtoMessage() {}

func (x *PostResp) ProtoReflect() protoreflect.Message {
	mi := &file_driftnode_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostResp.ProtoReflect.Descriptor instead.
func (*PostResp) Descriptor() ([]byte, []int) {
	return file_driftnode_proto_rawDescGZIP(), []int{9}
}

func (x *PostResp) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

// LikeReq creates a Like event targeting the given post event id. Passphrase
// unlocks the signing key; omit when the daemon is already unlocked.
type LikeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Passphrase    string                 `protobuf:"bytes,2,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeReq) Reset() {
	*x = LikeReq{}
	mi := &file_driftnode_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeReq) ProtoMessage() {}

func (x *LikeReq) ProtoReflect() protoreflect.Message {
	mi := &file_driftnode_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeReq.ProtoReflect.Descriptor instead.
func (*LikeReq) Descriptor() ([]byte, []int) {
	return file_driftnode_proto_rawDescGZIP(), []int{10}
}

func (x *LikeReq) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *LikeReq) GetPassphrase() string {
	if x != nil {
		return x.Passphrase
	}
	return ""
}

// LikeResp reports the created event id.
type LikeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeResp) Reset() {
	*x = LikeResp{}
	mi := &file_driftnode_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeResp) ProtoMessage() {}

func (x *LikeResp) ProtoReflect() protoreflect.Message {
	mi := &file_driftnode_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeResp.ProtoReflect.Descriptor instead.
func (*LikeResp) Descriptor() ([]byte, []int) {
	return file_driftnode_proto_rawDescGZIP(), []int{11}
}

func (x *LikeResp) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

// FetchLikesReq asks the daemon to query connected zens for Like events
// targeting the given post ids. This is an on-demand, best-effort fetch:
// the daemon dials each connected zen and requests any Like events it holds
// whose target_id matches one of the requested ids. Expensive, user-triggered.
type FetchLikesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostIds       []string               `protobuf:"bytes,1,rep,name=post_ids,json=postIds,proto3" json:"post_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchLikesReq) Reset() {
	*x = FetchLikesReq{}
	mi := &file_driftnode_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchLikesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchLikesReq) ProtoMessage() {}

func (x *FetchLikesReq) ProtoReflect() protoreflect.Message {
	mi := &file_driftnode_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchLikesReq.ProtoReflect.Descriptor instead.
func (*FetchLikesReq) Descriptor() ([]byte, []int) {
	return file_driftnode_proto_rawDescGZIP(), []int{12}
}

func (x *FetchLikesReq) GetPostIds() []string {
	if x != nil {
		return x.PostIds
	}
	return nil
}

// FetchLikesResp reports the like events received from connected zens.
type FetchLikesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LikeEventIds  []string               `protobuf:"bytes,1,rep,name=like_event_ids,json=likeEventIds,proto3" json:"like_event_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchLikesResp) Reset() {
	*x = FetchLikesResp{}
	mi := &file_driftnode_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchLikesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchLikesResp) ProtoMessage() {}

func (x *FetchLikesResp) ProtoReflect() protoreflect.Message {
	mi := &file_driftnode_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchLikesResp.ProtoReflect.Descriptor instead.
func (*FetchLikesResp) Descriptor() ([]byte, []int) {
	return file_driftnode_proto_rawDescGZIP(), []int{13}
}

func (x *FetchLikesResp) GetLikeEventIds() []string {
	if x != nil {
		return x.LikeEventIds
	}
	return nil
}

// ProfileReq sets the display name. Passphrase unlocks the signing key.
type ProfileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Passphrase    string                 `protobuf:"bytes,2,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileReq) Reset() {
	*x = ProfileReq{}
	mi := &file_driftnode_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileReq) ProtoMessage() {}

func (x *ProfileReq) ProtoReflect() protoreflect.Message {
	mi := &file_driftnode_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileReq.ProtoReflect.Descriptor instead.
func (*ProfileReq) Descriptor() ([]byte, []int) {
	return file_driftnode_proto_rawDescGZIP(), []int{14}
}

func (x *ProfileReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProfileReq) GetPassphrase() string {
	if x != nil {
		return x.Passphrase
	}
	return ""
}

// DetailReq sets optional profile fields. At least one field is required.
type DetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bio           string                 `protobuf:"bytes,1,opt,name=bio,proto3" json:"bio,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Location      string                 `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	Passphrase    string                 `protobuf:"bytes,5,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetailReq) Reset() {
	*x = DetailReq{}
	mi := &file_driftnode_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailReq) ProtoMessage() {}

func (x *DetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_driftnode_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailReq.ProtoReflect.Descriptor instead.
func (*DetailReq) Descriptor() ([]byte, []int) {
	return file_driftnode_proto_rawDescGZIP(), []int{15}
}

func (x *DetailReq) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *DetailReq) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *DetailReq) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *DetailReq) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *DetailReq) GetPassphrase() string {
	if x != nil {
		return x.Passphrase
	}
	return ""
}

// Zen is a discovered or connected zen, keyed by its tailcat token.
type Zen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Identity      string                 `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Kind          string                 `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Verified      bool                   `protobuf:"varint,6,opt,name=verified,proto3" json:"verified,omitempty"`
	Pinned        bool                   `protobuf:"varint,7,opt,name=pinned,proto3" json:"pinned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Zen) Reset() {
	*x = Zen{}
	mi := &file_driftnode_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Zen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Zen) ProtoMessage() {}

func (x *Zen) ProtoReflect() protoreflect.Message {
	mi := &file_driftnode_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Zen.ProtoReflect.Descriptor instead.
func (*Zen) Descriptor() ([]byte, []int) {
	return file_driftnode_proto_rawDescGZIP(), []int{16}
}

func (x *Zen) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Zen) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *Zen) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Zen) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Zen) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Zen) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *Zen) GetPinned() bool {
	if x != nil {
		return x.Pinned
	}
	return false
}

// ZensResp lists known zens.
type ZensResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Zens          []*Zen                 `protobuf:"bytes,1,rep,name=zens,proto3" json:"zens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZensResp) Reset() {
	*x = ZensResp{}
	mi := &file_driftnode_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZensResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZensResp) ProtoMessage() {}

func (x *ZensResp) ProtoReflect() protoreflect.Message {
	mi := &file_driftnode_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZensResp.ProtoReflect.Descriptor instead.
func (*ZensResp) Descriptor() ([]byte, []int) {
	return file_driftnode_proto_rawDescGZIP(), []int{17}
}

func (x *ZensResp) GetZens() []*Zen {
	if x != nil {
		return x.Zens
	}
	return nil
}

// Identity is one row of the follows or followers list.
type Identity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Identity) Reset() {
	*x = Identity{}
	mi := &file_driftnode_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identity) ProtoMessage() {}

func (x *Identity) ProtoReflect() protoreflect.Message {
	mi := &file_driftnode_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identity.ProtoReflect.Descriptor instead.
func (*Identity) Descriptor() ([]byte, []int) {
	return file_driftnode_proto_rawDescGZIP(), []int{18}
}

func (x *Identity) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *Identity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// IdentitiesResp lists identities.
type IdentitiesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identities    []*Identity            `protobuf:"bytes,1,rep,name=identities,proto3" json:"identities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentitiesResp) Reset() {
	*x = IdentitiesResp{}
	mi := &file_driftnode_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentitiesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentitiesResp) ProtoMessage() {}

func (x *IdentitiesResp) ProtoReflect() protoreflect.Message {
	mi := &file_driftnode_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentitiesResp.ProtoReflect.Descriptor instead.
func (*IdentitiesResp) Descriptor() ([]byte, []int) {
	return file_driftnode_proto_rawDescGZIP(), []int{19}
}

func (x *IdentitiesResp) GetIdentities() []*Identity {
	if x != nil {
		return x.Identities
	}
	return nil
}

// FollowReq targets a zen by token or identity. Passphrase unlocks the key.
type FollowReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Passphrase    string                 `protobuf:"bytes,2,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowReq) Reset() {
	*x = FollowReq{}
	mi := &file_driftnode_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowReq) ProtoMessage() {}

func (x *FollowReq) ProtoReflect() protoreflect.Message {
	mi := &file_driftnode_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowReq.ProtoReflect.Descriptor instead.
func (*FollowReq) Descriptor() ([]byte, []int) {
	return file_driftnode_proto_rawDescGZIP(), []int{20}
}

func (x *FollowReq) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *FollowReq) GetPassphrase() string {
	if x != nil {
		return x.Passphrase
	}
	return ""
}

// FollowResp reports the followed identity.
type FollowResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Followed      string                 `protobuf:"bytes,1,opt,name=followed,proto3" json:"followed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowResp) Reset() {
	*x = FollowResp{}
	mi := &file_driftnode_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowResp) ProtoMessage() {}

func (x *FollowResp) ProtoReflect() protoreflect.Message {
	mi := &file_driftnode_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowResp.ProtoReflect.Descriptor instead.
func (*FollowResp) Descriptor() ([]byte, []int) {
	return file_driftnode_proto_rawDescGZIP(), []int{21}
}

func (x *FollowResp) GetFollowed() string {
	if x != nil {
		return x.Followed
	}
	return ""
}

// UnfollowReq targets a zen by identity. Passphrase unlocks the key.
type UnfollowReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Passphrase    string                 `protobuf:"bytes,2,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfollowReq) Reset() {
	*x = UnfollowReq{}
	mi := &file_driftnode_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfollowReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfollowReq) ProtoMessage() {}

func (x *UnfollowReq) ProtoReflect() protoreflect.Message {
	mi := &file_driftnode_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfollowReq.ProtoReflect.Descriptor instead.
func (*UnfollowReq) Descriptor() ([]byte, []int) {
	return file_driftnode_proto_rawDescGZIP(), []int{22}
}

func (x *UnfollowReq) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *UnfollowReq) GetPassphrase() string {
	if x != nil {
		return x.Passphrase
	}
	return ""
}

// UnfollowResp reports the unfollowed identity.
type UnfollowResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Unfollowed    string                 `protobuf:"bytes,1,opt,name=unfollowed,proto3" json:"unfollowed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfollowResp) Reset() {
	*x = UnfollowResp{}
	mi := &file_driftnode_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfollowResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfollowResp) ProtoMessage() {}

func (x *UnfollowResp) ProtoReflect() protoreflect.Message {
	mi := &file_driftnode_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfollowResp.ProtoReflect.Descriptor instead.
func (*UnfollowResp) Descriptor() ([]byte, []int) {
	return file_driftnode_proto_rawDescGZIP(), []int{23}
}

func (x *UnfollowResp) GetUnfollowed() string {
	if x != nil {
		return x.Unfollowed
	}
	return ""
}

// UnlockReq supplies the passphrase to decrypt the signing key.
type UnlockReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Passphrase    string                 `protobuf:"bytes,1,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockReq) Reset() {
	*x = UnlockReq{}
	mi := &file_driftnode_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockReq) ProtoMessage() {}

func (x *UnlockReq) ProtoReflect() protoreflect.Message {
	mi := &file_driftnode_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockReq.ProtoReflect.Descriptor instead.
func (*UnlockReq) Descriptor() ([]byte, []int) {
	return file_driftnode_proto_rawDescGZIP(), []int{24}
}

func (x *UnlockReq) GetPassphrase() string {
	if x != nil {
		return x.Passphrase
	}
	return ""
}

// UnlockResp reports the unlocked identity.
type UnlockResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Identity      string                 `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockResp) Reset() {
	*x = UnlockResp{}
	mi := &file_driftnode_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockResp) ProtoMessage() {}

func (x *UnlockResp) ProtoReflect() protoreflect.Message {
	mi := &file_driftnode_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockResp.ProtoReflect.Descriptor instead.
func (*UnlockResp) Descriptor() ([]byte, []int) {
	return file_driftnode_proto_rawDescGZIP(), []int{25}
}

func (x *UnlockResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UnlockResp) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

// StatusResp is the daemon health snapshot.
type StatusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Running       bool                   `protobuf:"varint,1,opt,name=running,proto3" json:"running,omitempty"`
	Zens          int32                  `protobuf:"varint,2,opt,name=zens,proto3" json:"zens,omitempty"`
	Socket        string                 `protobuf:"bytes,3,opt,name=socket,proto3" json:"socket,omitempty"`
	Transport     bool                   `protobuf:"varint,4,opt,name=transport,proto3" json:"transport,omitempty"`
	Unlocked      bool                   `protobuf:"varint,5,opt,name=unlocked,proto3" json:"unlocked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResp) Reset() {
	*x = StatusResp{}
	mi := &file_driftnode_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResp) ProtoMessage() {}

func (x *StatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_driftnode_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResp.ProtoReflect.Descriptor instead.
func (*StatusResp) Descriptor() ([]byte, []int) {
	return file_driftnode_proto_rawDescGZIP(), []int{26}
}

func (x *StatusResp) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *StatusResp) GetZens() int32 {
	if x != nil {
		return x.Zens
	}
	return 0
}

func (x *StatusResp) GetSocket() string {
	if x != nil {
		return x.Socket
	}
	return ""
}

func (x *StatusResp) GetTransport() bool {
	if x != nil {
		return x.Transport
	}
	return false
}

func (x *StatusResp) GetUnlocked() bool {
	if x != nil {
		return x.Unlocked
	}
	return false
}

// RotateKeyResp reports the new tailcat address token after a key rotation.
type RotateKeyResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateKeyResp) Reset() {
	*x = RotateKeyResp{}
	mi := &file_driftnode_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateKeyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateKeyResp) ProtoMessage() {}

func (x *RotateKeyResp) ProtoReflect() protoreflect.Message {
	mi := &file_driftnode_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateKeyResp.ProtoReflect.Descriptor instead.
func (*RotateKeyResp) Descriptor() ([]byte, []int) {
	return file_driftnode_proto_rawDescGZIP(), []int{27}
}

func (x *RotateKeyResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// SubscribeReq has no parameters; the stream sends a Snapshot first, then
// incremental diff events.
type SubscribeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeReq) Reset() {
	*x = SubscribeReq{}
	mi := &file_driftnode_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeReq) ProtoMessage() {}

func (x *SubscribeReq) ProtoReflect() protoreflect.Message {
	mi := &file_driftnode_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeReq.ProtoReflect.Descriptor instead.
func (*SubscribeReq) Descriptor() ([]byte, []int) {
	return file_driftnode_proto_rawDescGZIP(), []int{28}
}

// Event is one message on the subscribe stream. The first is always a
// Snapshot; later events are diffs that the client applies in place by key.
type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Event_Snapshot
	//	*Event_FeedDiff
	//	*Event_ZenUpsert
	//	*Event_ZenRemove
	//	*Event_FollowsDiff
	//	*Event_FollowersDiff
	//	*Event_StatusDiff
	Kind          isEvent_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_driftnode_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_driftnode_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_driftnode_proto_rawDescGZIP(), []int{29}
}

func (x *Event) GetKind() isEvent_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Event) GetSnapshot() *Snapshot {
	if x != nil {
		if x, ok := x.Kind.(*Event_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

func (x *Event) GetFeedDiff() *FeedDiff {
	if x != nil {
		if x, ok := x.Kind.(*Event_FeedDiff); ok {
			return x.FeedDiff
		}
	}
	return nil
}

func (x *Event) GetZenUpsert() *ZenUpsert {
	if x != nil {
		if x, ok := x.Kind.(*Event_ZenUpsert); ok {
			return x.ZenUpsert
		}
	}
	return nil
}

func (x *Event) GetZenRemove() *ZenRemove {
	if x != nil {
		if x, ok := x.Kind.(*Event_ZenRemove); ok {
			return x.ZenRemove
		}
	}
	return nil
}

func (x *Event) GetFollowsDiff() *FollowsDiff {
	if x != nil {
		if x, ok := x.Kind.(*Event_FollowsDiff); ok {
			return x.FollowsDiff
		}
	}
	return nil
}

func (x *Event) GetFollowersDiff() *FollowersDiff {
	if x != nil {
		if x, ok := x.Kind.(*Event_FollowersDiff); ok {
			return x.FollowersDiff
		}
	}
	return nil
}

func (x *Event) GetStatusDiff() *StatusDiff {
	if x != nil {
		if x, ok := x.Kind.(*Event_StatusDiff); ok {
			return x.StatusDiff
		}
	}
	return nil
}

type isEvent_Kind interface {
	isEvent_Kind()
}

type Event_Snapshot struct {
	Snapshot *Snapshot `protobuf:"bytes,1,opt,name=snapshot,proto3,oneof"`
}

type Event_FeedDiff struct {
	FeedDiff *FeedDiff `protobuf:"bytes,2,opt,name=feed_diff,json=feedDiff,proto3,oneof"`
}

type Event_ZenUpsert struct {
	ZenUpsert *ZenUpsert `protobuf:"bytes,3,opt,name=zen_upsert,json=zenUpsert,proto3,oneof"`
}

type Event_ZenRemove struct {
	ZenRemove *ZenRemove `protobuf:"bytes,4,opt,name=zen_remove,json=zenRemove,proto3,oneof"`
}

type Event_FollowsDiff struct {
	FollowsDiff *FollowsDiff `protobuf:"bytes,5,opt,name=follows_diff,json=followsDiff,proto3,oneof"`
}

type Event_FollowersDiff struct {
	FollowersDiff *FollowersDiff `protobuf:"bytes,6,opt,name=followers_diff,json=followersDiff,proto3,oneof"`
}

type Event_StatusDiff struct {
	StatusDiff *StatusDiff `protobuf:"bytes,7,opt,name=status_diff,json=statusDiff,proto3,oneof"`
}

func (*Event_Snapshot) isEvent_Kind() {}

func (*Event_FeedDiff) isEvent_Kind() {}

func (*Event_ZenUpsert) isEvent_Kind() {}

func (*Event_ZenRemove) isEvent_Kind() {}

func (*Event_FollowsDiff) isEvent_Kind() {}

func (*Event_FollowersDiff) isEvent_Kind() {}

func (*Event_StatusDiff) isEvent_Kind() {}

// Snapshot is the initial subscribe event: the full state of all panels.
type Snapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Feed          []*FeedItem            `protobuf:"bytes,1,rep,name=feed,proto3" json:"feed,omitempty"`
	Zens          []*Zen                 `protobuf:"bytes,2,rep,name=zens,proto3" json:"zens,omitempty"`
	Follows       []*Identity            `protobuf:"bytes,3,rep,name=follows,proto3" json:"follows,omitempty"`
	Followers     []*Identity            `protobuf:"bytes,4,rep,name=followers,proto3" json:"followers,omitempty"`
	Status        *StatusDiff            `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_driftnode_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_driftnode_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_driftnode_proto_rawDescGZIP(), []int{30}
}

func (x *Snapshot) GetFeed() []*FeedItem {
	if x != nil {
		return x.Feed
	}
	return nil
}

func (x *Snapshot) GetZens() []*Zen {
	if x != nil {
		return x.Zens
	}
	return nil
}

func (x *Snapshot) GetFollows() []*Identity {
	if x != nil {
		return x.Follows
	}
	return nil
}

func (x *Snapshot) GetFollowers() []*Identity {
	if x != nil {
		return x.Followers
	}
	return nil
}

func (x *Snapshot) GetStatus() *StatusDiff {
	if x != nil {
		return x.Status
	}
	return nil
}

// FeedDiff adds newly merged posts, newest-first.
type FeedDiff struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Add           []*FeedItem            `protobuf:"bytes,1,rep,name=add,proto3" json:"add,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedDiff) Reset() {
	*x = FeedDiff{}
	mi := &file_driftnode_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedDiff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedDiff) ProtoMessage() {}

func (x *FeedDiff) ProtoReflect() protoreflect.Message {
	mi := &file_driftnode_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedDiff.ProtoReflect.Descriptor instead.
func (*FeedDiff) Descriptor() ([]byte, []int) {
	return file_driftnode_proto_rawDescGZIP(), []int{31}
}

func (x *FeedDiff) GetAdd() []*FeedItem {
	if x != nil {
		return x.Add
	}
	return nil
}

// ZenUpsert updates or inserts one zen by its token id.
type ZenUpsert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Zen           *Zen                   `protobuf:"bytes,1,opt,name=zen,proto3" json:"zen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZenUpsert) Reset() {
	*x = ZenUpsert{}
	mi := &file_driftnode_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZenUpsert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZenUpsert) ProtoMessage() {}

func (x *ZenUpsert) ProtoReflect() protoreflect.Message {
	mi := &file_driftnode_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZenUpsert.ProtoReflect.Descriptor instead.
func (*ZenUpsert) Descriptor() ([]byte, []int) {
	return file_driftnode_proto_rawDescGZIP(), []int{32}
}

func (x *ZenUpsert) GetZen() *Zen {
	if x != nil {
		return x.Zen
	}
	return nil
}

// ZenRemove drops one zen by its token id.
type ZenRemove struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZenRemove) Reset() {
	*x = ZenRemove{}
	mi := &file_driftnode_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZenRemove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZenRemove) ProtoMessage() {}

func (x *ZenRemove) ProtoReflect() protoreflect.Message {
	mi := &file_driftnode_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZenRemove.ProtoReflect.Descriptor instead.
func (*ZenRemove) Descriptor() ([]byte, []int) {
	return file_driftnode_proto_rawDescGZIP(), []int{33}
}

func (x *ZenRemove) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// FollowsDiff adds or removes one followed identity.
type FollowsDiff struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Add           []*Identity            `protobuf:"bytes,1,rep,name=add,proto3" json:"add,omitempty"`
	Remove        string                 `protobuf:"bytes,2,opt,name=remove,proto3" json:"remove,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowsDiff) Reset() {
	*x = FollowsDiff{}
	mi := &file_driftnode_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowsDiff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowsDiff) ProtoMessage() {}

func (x *FollowsDiff) ProtoReflect() protoreflect.Message {
	mi := &file_driftnode_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowsDiff.ProtoReflect.Descriptor instead.
func (*FollowsDiff) Descriptor() ([]byte, []int) {
	return file_driftnode_proto_rawDescGZIP(), []int{34}
}

func (x *FollowsDiff) GetAdd() []*Identity {
	if x != nil {
		return x.Add
	}
	return nil
}

func (x *FollowsDiff) GetRemove() string {
	if x != nil {
		return x.Remove
	}
	return ""
}

// FollowersDiff adds or removes one follower identity.
type FollowersDiff struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Add           []*Identity            `protobuf:"bytes,1,rep,name=add,proto3" json:"add,omitempty"`
	Remove        string                 `protobuf:"bytes,2,opt,name=remove,proto3" json:"remove,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowersDiff) Reset() {
	*x = FollowersDiff{}
	mi := &file_driftnode_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowersDiff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowersDiff) ProtoMessage() {}

func (x *FollowersDiff) ProtoReflect() protoreflect.Message {
	mi := &file_driftnode_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowersDiff.ProtoReflect.Descriptor instead.
func (*FollowersDiff) Descriptor() ([]byte, []int) {
	return file_driftnode_proto_rawDescGZIP(), []int{35}
}

func (x *FollowersDiff) GetAdd() []*Identity {
	if x != nil {
		return x.Add
	}
	return nil
}

func (x *FollowersDiff) GetRemove() string {
	if x != nil {
		return x.Remove
	}
	return ""
}

// StatusDiff is an updated health snapshot pushed on state changes.
type StatusDiff struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Running       bool                   `protobuf:"varint,1,opt,name=running,proto3" json:"running,omitempty"`
	Zens          int32                  `protobuf:"varint,2,opt,name=zens,proto3" json:"zens,omitempty"`
	Transport     bool                   `protobuf:"varint,3,opt,name=transport,proto3" json:"transport,omitempty"`
	Unlocked      bool                   `protobuf:"varint,4,opt,name=unlocked,proto3" json:"unlocked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusDiff) Reset() {
	*x = StatusDiff{}
	mi := &file_driftnode_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusDiff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusDiff) ProtoMessage() {}

func (x *StatusDiff) ProtoReflect() protoreflect.Message {
	mi := &file_driftnode_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusDiff.ProtoReflect.Descriptor instead.
func (*StatusDiff) Descriptor() ([]byte, []int) {
	return file_driftnode_proto_rawDescGZIP(), []int{36}
}

func (x *StatusDiff) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *StatusDiff) GetZens() int32 {
	if x != nil {
		return x.Zens
	}
	return 0
}

func (x *StatusDiff) GetTransport() bool {
	if x != nil {
		return x.Transport
	}
	return false
}

func (x *StatusDiff) GetUnlocked() bool {
	if x != nil {
		return x.Unlocked
	}
	return false
}

var File_driftnode_proto protoreflect.FileDescriptor

const file_driftnode_proto_rawDesc = "" +
	"\n" +
	"\x0fdriftnode.proto\x12\fdriftnode.v1\"\a\n" +
	"\x05Empty\"#\n" +
	"\tEmptyResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\x82\x02\n" +
	"\n" +
	"WhoamiResp\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x16\n" +
	"\x06stable\x18\x03 \x01(\bR\x06stable\x12!\n" +
	"\fdisplay_name\x18\x04 \x01(\tR\vdisplayName\x12\x1d\n" +
	"\n" +
	"has_avatar\x18\x05 \x01(\bR\thasAvatar\x12\x10\n" +
	"\x03bio\x18\x06 \x01(\tR\x03bio\x12\x1d\n" +
	"\n" +
	"first_name\x18\a \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\b \x01(\tR\blastName\x12\x1a\n" +
	"\blocation\x18\t \x01(\tR\blocation\")\n" +
	"\vIdentityReq\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\"(\n" +
	"\n" +
	"VerifyResp\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\"\xaf\x01\n" +
	"\bFeedItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04text\x18\x05 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"like_count\x18\x06 \x01(\x05R\tlikeCount\x12\x16\n" +
	"\x06likers\x18\a \x03(\tR\x06likers\"R\n" +
	"\vFeedPageReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04mine\x18\x02 \x01(\bR\x04mine\x12\x1b\n" +
	"\tall_likes\x18\x03 \x01(\bR\ballLikes\"W\n" +
	"\fFeedPageResp\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.driftnode.v1.FeedItemR\x05items\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\"Z\n" +
	"\aPostReq\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1e\n" +
	"\n" +
	"passphrase\x18\x02 \x01(\tR\n" +
	"passphrase\x12\x1b\n" +
	"\tparent_id\x18\x03 \x01(\tR\bparentId\"%\n" +
	"\bPostResp\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\"B\n" +
	"\aLikeReq\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x12\x1e\n" +
	"\n" +
	"passphrase\x18\x02 \x01(\tR\n" +
	"passphrase\"%\n" +
	"\bLikeResp\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\"*\n" +
	"\rFetchLikesReq\x12\x19\n" +
	"\bpost_ids\x18\x01 \x03(\tR\apostIds\"6\n" +
	"\x0eFetchLikesResp\x12$\n" +
	"\x0elike_event_ids\x18\x01 \x03(\tR\flikeEventIds\"@\n" +
	"\n" +
	"ProfileReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"passphrase\x18\x02 \x01(\tR\n" +
	"passphrase\"\x95\x01\n" +
	"\tDetailReq\x12\x10\n" +
	"\x03bio\x18\x01 \x01(\tR\x03bio\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x1a\n" +
	"\blocation\x18\x04 \x01(\tR\blocation\x12\x1e\n" +
	"\n" +
	"passphrase\x18\x05 \x01(\tR\n" +
	"passphrase\"\xa5\x01\n" +
	"\x03Zen\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bidentity\x18\x02 \x01(\tR\bidentity\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1a\n" +
	"\bverified\x18\x06 \x01(\bR\bverified\x12\x16\n" +
	"\x06pinned\x18\a \x01(\bR\x06pinned\"1\n" +
	"\bZensResp\x12%\n" +
	"\x04zens\x18\x01 \x03(\v2\x11.driftnode.v1.ZenR\x04zens\":\n" +
	"\bIdentity\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"H\n" +
	"\x0eIdentitiesResp\x126\n" +
	"\n" +
	"identities\x18\x01 \x03(\v2\x16.driftnode.v1.IdentityR\n" +
	"identities\"C\n" +
	"\tFollowReq\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x1e\n" +
	"\n" +
	"passphrase\x18\x02 \x01(\tR\n" +
	"passphrase\"(\n" +
	"\n" +
	"FollowResp\x12\x1a\n" +
	"\bfollowed\x18\x01 \x01(\tR\bfollowed\"E\n" +
	"\vUnfollowReq\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x1e\n" +
	"\n" +
	"passphrase\x18\x02 \x01(\tR\n" +
	"passphrase\".\n" +
	"\fUnfollowResp\x12\x1e\n" +
	"\n" +
	"unfollowed\x18\x01 \x01(\tR\n" +
	"unfollowed\"+\n" +
	"\tUnlockReq\x12\x1e\n" +
	"\n" +
	"passphrase\x18\x01 \x01(\tR\n" +
	"passphrase\"@\n" +
	"\n" +
	"UnlockResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1a\n" +
	"\bidentity\x18\x02 \x01(\tR\bidentity\"\x8c\x01\n" +
	"\n" +
	"StatusResp\x12\x18\n" +
	"\arunning\x18\x01 \x01(\bR\arunning\x12\x12\n" +
	"\x04zens\x18\x02 \x01(\x05R\x04zens\x12\x16\n" +
	"\x06socket\x18\x03 \x01(\tR\x06socket\x12\x1c\n" +
	"\ttransport\x18\x04 \x01(\bR\ttransport\x12\x1a\n" +
	"\bunlocked\x18\x05 \x01(\bR\bunlocked\"%\n" +
	"\rRotateKeyResp\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x0e\n" +
	"\fSubscribeReq\"\xb3\x03\n" +
	"\x05Event\x124\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x16.driftnode.v1.SnapshotH\x00R\bsnapshot\x125\n" +
	"\tfeed_diff\x18\x02 \x01(\v2\x16.driftnode.v1.FeedDiffH\x00R\bfeedDiff\x128\n" +
	"\n" +
	"zen_upsert\x18\x03 \x01(\v2\x17.driftnode.v1.ZenUpsertH\x00R\tzenUpsert\x128\n" +
	"\n" +
	"zen_remove\x18\x04 \x01(\v2\x17.driftnode.v1.ZenRemoveH\x00R\tzenRemove\x12>\n" +
	"\ffollows_diff\x18\x05 \x01(\v2\x19.driftnode.v1.FollowsDiffH\x00R\vfollowsDiff\x12D\n" +
	"\x0efollowers_diff\x18\x06 \x01(\v2\x1b.driftnode.v1.FollowersDiffH\x00R\rfollowersDiff\x12;\n" +
	"\vstatus_diff\x18\a \x01(\v2\x18.driftnode.v1.StatusDiffH\x00R\n" +
	"statusDiffB\x06\n" +
	"\x04kind\"\xf7\x01\n" +
	"\bSnapshot\x12*\n" +
	"\x04feed\x18\x01 \x03(\v2\x16.driftnode.v1.FeedItemR\x04feed\x12%\n" +
	"\x04zens\x18\x02 \x03(\v2\x11.driftnode.v1.ZenR\x04zens\x120\n" +
	"\afollows\x18\x03 \x03(\v2\x16.driftnode.v1.IdentityR\afollows\x124\n" +
	"\tfollowers\x18\x04 \x03(\v2\x16.driftnode.v1.IdentityR\tfollowers\x120\n" +
	"\x06status\x18\x05 \x01(\v2\x18.driftnode.v1.StatusDiffR\x06status\"4\n" +
	"\bFeedDiff\x12(\n" +
	"\x03add\x18\x01 \x03(\v2\x16.driftnode.v1.FeedItemR\x03add\"0\n" +
	"\tZenUpsert\x12#\n" +
	"\x03zen\x18\x01 \x01(\v2\x11.driftnode.v1.ZenR\x03zen\"\x1b\n" +
	"\tZenRemove\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"O\n" +
	"\vFollowsDiff\x12(\n" +
	"\x03add\x18\x01 \x03(\v2\x16.driftnode.v1.IdentityR\x03add\x12\x16\n" +
	"\x06remove\x18\x02 \x01(\tR\x06remove\"Q\n" +
	"\rFollowersDiff\x12(\n" +
	"\x03add\x18\x01 \x03(\v2\x16.driftnode.v1.IdentityR\x03add\x12\x16\n" +
	"\x06remove\x18\x02 \x01(\tR\x06remove\"t\n" +
	"\n" +
	"StatusDiff\x12\x18\n" +
	"\arunning\x18\x01 \x01(\bR\arunning\x12\x12\n" +
	"\x04zens\x18\x02 \x01(\x05R\x04zens\x12\x1c\n" +
	"\ttransport\x18\x03 \x01(\bR\ttransport\x12\x1a\n" +
	"\bunlocked\x18\x04 \x01(\bR\bunlocked2\xfc\n" +
	"\n" +
	"\tDriftnode\x127\n" +
	"\x06Whoami\x12\x13.driftnode.v1.Empty\x1a\x18.driftnode.v1.WhoamiResp\x12<\n" +
	"\aFollows\x12\x13.driftnode.v1.Empty\x1a\x1c.driftnode.v1.IdentitiesResp\x12>\n" +
	"\tFollowers\x12\x13.driftnode.v1.Empty\x1a\x1c.driftnode.v1.IdentitiesResp\x125\n" +
	"\x04Post\x12\x15.driftnode.v1.PostReq\x1a\x16.driftnode.v1.PostResp\x125\n" +
	"\x04Like\x12\x15.driftnode.v1.LikeReq\x1a\x16.driftnode.v1.LikeResp\x12G\n" +
	"\n" +
	"FetchLikes\x12\x1b.driftnode.v1.FetchLikesReq\x1a\x1c.driftnode.v1.FetchLikesResp\x12<\n" +
	"\aProfile\x12\x18.driftnode.v1.ProfileReq\x1a\x17.driftnode.v1.EmptyResp\x12:\n" +
	"\x06Detail\x12\x17.driftnode.v1.DetailReq\x1a\x17.driftnode.v1.EmptyResp\x123\n" +
	"\x04Zens\x12\x13.driftnode.v1.Empty\x1a\x16.driftnode.v1.ZensResp\x12=\n" +
	"\x06Verify\x12\x19.driftnode.v1.IdentityReq\x1a\x18.driftnode.v1.VerifyResp\x12?\n" +
	"\bUnverify\x12\x19.driftnode.v1.IdentityReq\x1a\x18.driftnode.v1.VerifyResp\x12:\n" +
	"\x03Pin\x12\x19.driftnode.v1.IdentityReq\x1a\x18.driftnode.v1.VerifyResp\x12<\n" +
	"\x05Unpin\x12\x19.driftnode.v1.IdentityReq\x1a\x18.driftnode.v1.VerifyResp\x12;\n" +
	"\x06Follow\x12\x17.driftnode.v1.FollowReq\x1a\x18.driftnode.v1.FollowResp\x12A\n" +
	"\bUnfollow\x12\x19.driftnode.v1.UnfollowReq\x1a\x1a.driftnode.v1.UnfollowResp\x12;\n" +
	"\x06Unlock\x12\x17.driftnode.v1.UnlockReq\x1a\x18.driftnode.v1.UnlockResp\x124\n" +
	"\x04Lock\x12\x13.driftnode.v1.Empty\x1a\x17.driftnode.v1.EmptyResp\x124\n" +
	"\x04Sync\x12\x13.driftnode.v1.Empty\x1a\x17.driftnode.v1.EmptyResp\x124\n" +
	"\x04Stop\x12\x13.driftnode.v1.Empty\x1a\x17.driftnode.v1.EmptyResp\x127\n" +
	"\x06Status\x12\x13.driftnode.v1.Empty\x1a\x18.driftnode.v1.StatusResp\x12=\n" +
	"\tRotateKey\x12\x13.driftnode.v1.Empty\x1a\x1b.driftnode.v1.RotateKeyResp\x12>\n" +
	"\tSubscribe\x12\x1a.driftnode.v1.SubscribeReq\x1a\x13.driftnode.v1.Event0\x01\x12A\n" +
	"\bFeedPage\x12\x19.driftnode.v1.FeedPageReq\x1a\x1a.driftnode.v1.FeedPageRespB2Z0driftnode/internal/proto/driftnodepb;driftnodepbb\x06proto3"

var (
	file_driftnode_proto_rawDescOnce sync.Once
	file_driftnode_proto_rawDescData []byte
)

func file_driftnode_proto_rawDescGZIP() []byte {
	file_driftnode_proto_rawDescOnce.Do(func() {
		file_driftnode_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_driftnode_proto_rawDesc), len(file_driftnode_proto_rawDesc)))
	})
	return file_driftnode_proto_rawDescData
}

var file_driftnode_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_driftnode_proto_goTypes = []any{
	(*Empty)(nil),          // 0: driftnode.v1.Empty
	(*EmptyResp)(nil),      // 1: driftnode.v1.EmptyResp
	(*WhoamiResp)(nil),     // 2: driftnode.v1.WhoamiResp
	(*IdentityReq)(nil),    // 3: driftnode.v1.IdentityReq
	(*VerifyResp)(nil),     // 4: driftnode.v1.VerifyResp
	(*FeedItem)(nil),       // 5: driftnode.v1.FeedItem
	(*FeedPageReq)(nil),    // 6: driftnode.v1.FeedPageReq
	(*FeedPageResp)(nil),   // 7: driftnode.v1.FeedPageResp
	(*PostReq)(nil),        // 8: driftnode.v1.PostReq
	(*PostResp)(nil),       // 9: driftnode.v1.PostResp
	(*LikeReq)(nil),        // 10: driftnode.v1.LikeReq
	(*LikeResp)(nil),       // 11: driftnode.v1.LikeResp
	(*FetchLikesReq)(nil),  // 12: driftnode.v1.FetchLikesReq
	(*FetchLikesResp)(nil), // 13: driftnode.v1.FetchLikesResp
	(*ProfileReq)(nil),     // 14: driftnode.v1.ProfileReq
	(*DetailReq)(nil),      // 15: driftnode.v1.DetailReq
	(*Zen)(nil),            // 16: driftnode.v1.Zen
	(*ZensResp)(nil),       // 17: driftnode.v1.ZensResp
	(*Identity)(nil),       // 18: driftnode.v1.Identity
	(*IdentitiesResp)(nil), // 19: driftnode.v1.IdentitiesResp
	(*FollowReq)(nil),      // 20: driftnode.v1.FollowReq
	(*FollowResp)(nil),     // 21: driftnode.v1.FollowResp
	(*UnfollowReq)(nil),    // 22: driftnode.v1.UnfollowReq
	(*UnfollowResp)(nil),   // 23: driftnode.v1.UnfollowResp
	(*UnlockReq)(nil),      // 24: driftnode.v1.UnlockReq
	(*UnlockResp)(nil),     // 25: driftnode.v1.UnlockResp
	(*StatusResp)(nil),     // 26: driftnode.v1.StatusResp
	(*RotateKeyResp)(nil),  // 27: driftnode.v1.RotateKeyResp
	(*SubscribeReq)(nil),   // 28: driftnode.v1.SubscribeReq
	(*Event)(nil),          // 29: driftnode.v1.Event
	(*Snapshot)(nil),       // 30: driftnode.v1.Snapshot
	(*FeedDiff)(nil),       // 31: driftnode.v1.FeedDiff
	(*ZenUpsert)(nil),      // 32: driftnode.v1.ZenUpsert
	(*ZenRemove)(nil),      // 33: driftnode.v1.ZenRemove
	(*FollowsDiff)(nil),    // 34: driftnode.v1.FollowsDiff
	(*FollowersDiff)(nil),  // 35: driftnode.v1.FollowersDiff
	(*StatusDiff)(nil),     // 36: driftnode.v1.StatusDiff
}
var file_driftnode_proto_depIdxs = []int32{
	5,  // 0: driftnode.v1.FeedPageResp.items:type_name -> driftnode.v1.FeedItem
	16, // 1: driftnode.v1.ZensResp.zens:type_name -> driftnode.v1.Zen
	18, // 2: driftnode.v1.IdentitiesResp.identities:type_name -> driftnode.v1.Identity
	30, // 3: driftnode.v1.Event.snapshot:type_name -> driftnode.v1.Snapshot
	31, // 4: driftnode.v1.Event.feed_diff:type_name -> driftnode.v1.FeedDiff
	32, // 5: driftnode.v1.Event.zen_upsert:type_name -> driftnode.v1.ZenUpsert
	33, // 6: driftnode.v1.Event.zen_remove:type_name -> driftnode.v1.ZenRemove
	34, // 7: driftnode.v1.Event.follows_diff:type_name -> driftnode.v1.FollowsDiff
	35, // 8: driftnode.v1.Event.followers_diff:type_name -> driftnode.v1.FollowersDiff
	36, // 9: driftnode.v1.Event.status_diff:type_name -> driftnode.v1.StatusDiff
	5,  // 10: driftnode.v1.Snapshot.feed:type_name -> driftnode.v1.FeedItem
	16, // 11: driftnode.v1.Snapshot.zens:type_name -> driftnode.v1.Zen
	18, // 12: driftnode.v1.Snapshot.follows:type_name -> driftnode.v1.Identity
	18, // 13: driftnode.v1.Snapshot.followers:type_name -> driftnode.v1.Identity
	36, // 14: driftnode.v1.Snapshot.status:type_name -> driftnode.v1.StatusDiff
	5,  // 15: driftnode.v1.FeedDiff.add:type_name -> driftnode.v1.FeedItem
	16, // 16: driftnode.v1.ZenUpsert.zen:type_name -> driftnode.v1.Zen
	18, // 17: driftnode.v1.FollowsDiff.add:type_name -> driftnode.v1.Identity
	18, // 18: driftnode.v1.FollowersDiff.add:type_name -> driftnode.v1.Identity
	0,  // 19: driftnode.v1.Driftnode.Whoami:input_type -> driftnode.v1.Empty
	0,  // 20: driftnode.v1.Driftnode.Follows:input_type -> driftnode.v1.Empty
	0,  // 21: driftnode.v1.Driftnode.Followers:input_type -> driftnode.v1.Empty
	8,  // 22: driftnode.v1.Driftnode.Post:input_type -> driftnode.v1.PostReq
	10, // 23: driftnode.v1.Driftnode.Like:input_type -> driftnode.v1.LikeReq
	12, // 24: driftnode.v1.Driftnode.FetchLikes:input_type -> driftnode.v1.FetchLikesReq
	14, // 25: driftnode.v1.Driftnode.Profile:input_type -> driftnode.v1.ProfileReq
	15, // 26: driftnode.v1.Driftnode.Detail:input_type -> driftnode.v1.DetailReq
	0,  // 27: driftnode.v1.Driftnode.Zens:input_type -> driftnode.v1.Empty
	3,  // 28: driftnode.v1.Driftnode.Verify:input_type -> driftnode.v1.IdentityReq
	3,  // 29: driftnode.v1.Driftnode.Unverify:input_type -> driftnode.v1.IdentityReq
	3,  // 30: driftnode.v1.Driftnode.Pin:input_type -> driftnode.v1.IdentityReq
	3,  // 31: driftnode.v1.Driftnode.Unpin:input_type -> driftnode.v1.IdentityReq
	20, // 32: driftnode.v1.Driftnode.Follow:input_type -> driftnode.v1.FollowReq
	22, // 33: driftnode.v1.Driftnode.Unfollow:input_type -> driftnode.v1.UnfollowReq
	24, // 34: driftnode.v1.Driftnode.Unlock:input_type -> driftnode.v1.UnlockReq
	0,  // 35: driftnode.v1.Driftnode.Lock:input_type -> driftnode.v1.Empty
	0,  // 36: driftnode.v1.Driftnode.Sync:input_type -> driftnode.v1.Empty
	0,  // 37: driftnode.v1.Driftnode.Stop:input_type -> driftnode.v1.Empty
	0,  // 38: driftnode.v1.Driftnode.Status:input_type -> driftnode.v1.Empty
	0,  // 39: driftnode.v1.Driftnode.RotateKey:input_type -> driftnode.v1.Empty
	28, // 40: driftnode.v1.Driftnode.Subscribe:input_type -> driftnode.v1.SubscribeReq
	6,  // 41: driftnode.v1.Driftnode.FeedPage:input_type -> driftnode.v1.FeedPageReq
	2,  // 42: driftnode.v1.Driftnode.Whoami:output_type -> driftnode.v1.WhoamiResp
	19, // 43: driftnode.v1.Driftnode.Follows:output_type -> driftnode.v1.IdentitiesResp
	19, // 44: driftnode.v1.Driftnode.Followers:output_type -> driftnode.v1.IdentitiesResp
	9,  // 45: driftnode.v1.Driftnode.Post:output_type -> driftnode.v1.PostResp
	11, // 46: driftnode.v1.Driftnode.Like:output_type -> driftnode.v1.LikeResp
	13, // 47: driftnode.v1.Driftnode.FetchLikes:output_type -> driftnode.v1.FetchLikesResp
	1,  // 48: driftnode.v1.Driftnode.Profile:output_type -> driftnode.v1.EmptyResp
	1,  // 49: driftnode.v1.Driftnode.Detail:output_type -> driftnode.v1.EmptyResp
	17, // 50: driftnode.v1.Driftnode.Zens:output_type -> driftnode.v1.ZensResp
	4,  // 51: driftnode.v1.Driftnode.Verify:output_type -> driftnode.v1.VerifyResp
	4,  // 52: driftnode.v1.Driftnode.Unverify:output_type -> driftnode.v1.VerifyResp
	4,  // 53: driftnode.v1.Driftnode.Pin:output_type -> driftnode.v1.VerifyResp
	4,  // 54: driftnode.v1.Driftnode.Unpin:output_type -> driftnode.v1.VerifyResp
	21, // 55: driftnode.v1.Driftnode.Follow:output_type -> driftnode.v1.FollowResp
	23, // 56: driftnode.v1.Driftnode.Unfollow:output_type -> driftnode.v1.UnfollowResp
	25, // 57: driftnode.v1.Driftnode.Unlock:output_type -> driftnode.v1.UnlockResp
	1,  // 58: driftnode.v1.Driftnode.Lock:output_type -> driftnode.v1.EmptyResp
	1,  // 59: driftnode.v1.Driftnode.Sync:output_type -> driftnode.v1.EmptyResp
	1,  // 60: driftnode.v1.Driftnode.Stop:output_type -> driftnode.v1.EmptyResp
	26, // 61: driftnode.v1.Driftnode.Status:output_type -> driftnode.v1.StatusResp
	27, // 62: driftnode.v1.Driftnode.RotateKey:output_type -> driftnode.v1.RotateKeyResp
	29, // 63: driftnode.v1.Driftnode.Subscribe:output_type -> driftnode.v1.Event
	7,  // 64: driftnode.v1.Driftnode.FeedPage:output_type -> driftnode.v1.FeedPageResp
	42, // [42:65] is the sub-list for method output_type
	19, // [19:42] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_driftnode_proto_init() }
func file_driftnode_proto_init() {
	if File_driftnode_proto != nil {
		return
	}
	file_driftnode_proto_msgTypes[29].OneofWrappers = []any{
		(*Event_Snapshot)(nil),
		(*Event_FeedDiff)(nil),
		(*Event_ZenUpsert)(nil),
		(*Event_ZenRemove)(nil),
		(*Event_FollowsDiff)(nil),
		(*Event_FollowersDiff)(nil),
		(*Event_StatusDiff)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_driftnode_proto_rawDesc), len(file_driftnode_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_driftnode_proto_goTypes,
		DependencyIndexes: file_driftnode_proto_depIdxs,
		MessageInfos:      file_driftnode_proto_msgTypes,
	}.Build()
	File_driftnode_proto = out.File
	file_driftnode_proto_goTypes = nil
	file_driftnode_proto_depIdxs = nil
}
