// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.1
// source: driftnode.proto

package driftnodepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Driftnode_Whoami_FullMethodName     = "/driftnode.v1.Driftnode/Whoami"
	Driftnode_Follows_FullMethodName    = "/driftnode.v1.Driftnode/Follows"
	Driftnode_Followers_FullMethodName  = "/driftnode.v1.Driftnode/Followers"
	Driftnode_Post_FullMethodName       = "/driftnode.v1.Driftnode/Post"
	Driftnode_Like_FullMethodName       = "/driftnode.v1.Driftnode/Like"
	Driftnode_FetchLikes_FullMethodName = "/driftnode.v1.Driftnode/FetchLikes"
	Driftnode_Profile_FullMethodName    = "/driftnode.v1.Driftnode/Profile"
	Driftnode_Detail_FullMethodName     = "/driftnode.v1.Driftnode/Detail"
	Driftnode_Zens_FullMethodName       = "/driftnode.v1.Driftnode/Zens"
	Driftnode_Verify_FullMethodName     = "/driftnode.v1.Driftnode/Verify"
	Driftnode_Unverify_FullMethodName   = "/driftnode.v1.Driftnode/Unverify"
	Driftnode_Follow_FullMethodName     = "/driftnode.v1.Driftnode/Follow"
	Driftnode_Unfollow_FullMethodName   = "/driftnode.v1.Driftnode/Unfollow"
	Driftnode_Unlock_FullMethodName     = "/driftnode.v1.Driftnode/Unlock"
	Driftnode_Lock_FullMethodName       = "/driftnode.v1.Driftnode/Lock"
	Driftnode_Sync_FullMethodName       = "/driftnode.v1.Driftnode/Sync"
	Driftnode_Stop_FullMethodName       = "/driftnode.v1.Driftnode/Stop"
	Driftnode_Status_FullMethodName     = "/driftnode.v1.Driftnode/Status"
	Driftnode_RotateKey_FullMethodName  = "/driftnode.v1.Driftnode/RotateKey"
	Driftnode_Subscribe_FullMethodName  = "/driftnode.v1.Driftnode/Subscribe"
	Driftnode_FeedPage_FullMethodName   = "/driftnode.v1.Driftnode/FeedPage"
)

// DriftnodeClient is the client API for Driftnode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Driftnode is the control-plane API the daemon exposes to the CLI and TUI
// over a Unix domain socket. Unary RPCs cover one-shot commands; Subscribe is
// a server stream of typed events that replaces the old polling model.
type DriftnodeClient interface {
	Whoami(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*WhoamiResp, error)
	Follows(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*IdentitiesResp, error)
	Followers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*IdentitiesResp, error)
	Post(ctx context.Context, in *PostReq, opts ...grpc.CallOption) (*PostResp, error)
	Like(ctx context.Context, in *LikeReq, opts ...grpc.CallOption) (*LikeResp, error)
	FetchLikes(ctx context.Context, in *FetchLikesReq, opts ...grpc.CallOption) (*FetchLikesResp, error)
	Profile(ctx context.Context, in *ProfileReq, opts ...grpc.CallOption) (*EmptyResp, error)
	Detail(ctx context.Context, in *DetailReq, opts ...grpc.CallOption) (*EmptyResp, error)
	Zens(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ZensResp, error)
	Verify(ctx context.Context, in *IdentityReq, opts ...grpc.CallOption) (*VerifyResp, error)
	Unverify(ctx context.Context, in *IdentityReq, opts ...grpc.CallOption) (*VerifyResp, error)
	Follow(ctx context.Context, in *FollowReq, opts ...grpc.CallOption) (*FollowResp, error)
	Unfollow(ctx context.Context, in *UnfollowReq, opts ...grpc.CallOption) (*UnfollowResp, error)
	Unlock(ctx context.Context, in *UnlockReq, opts ...grpc.CallOption) (*UnlockResp, error)
	Lock(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*EmptyResp, error)
	Sync(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*EmptyResp, error)
	Stop(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*EmptyResp, error)
	Status(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusResp, error)
	RotateKey(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RotateKeyResp, error)
	Subscribe(ctx context.Context, in *SubscribeReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
	FeedPage(ctx context.Context, in *FeedPageReq, opts ...grpc.CallOption) (*FeedPageResp, error)
}

type driftnodeClient struct {
	cc grpc.ClientConnInterface
}

func NewDriftnodeClient(cc grpc.ClientConnInterface) DriftnodeClient {
	return &driftnodeClient{cc}
}

func (c *driftnodeClient) Whoami(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*WhoamiResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WhoamiResp)
	err := c.cc.Invoke(ctx, Driftnode_Whoami_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driftnodeClient) Follows(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*IdentitiesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IdentitiesResp)
	err := c.cc.Invoke(ctx, Driftnode_Follows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driftnodeClient) Followers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*IdentitiesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IdentitiesResp)
	err := c.cc.Invoke(ctx, Driftnode_Followers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driftnodeClient) Post(ctx context.Context, in *PostReq, opts ...grpc.CallOption) (*PostResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostResp)
	err := c.cc.Invoke(ctx, Driftnode_Post_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driftnodeClient) Like(ctx context.Context, in *LikeReq, opts ...grpc.CallOption) (*LikeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LikeResp)
	err := c.cc.Invoke(ctx, Driftnode_Like_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driftnodeClient) FetchLikes(ctx context.Context, in *FetchLikesReq, opts ...grpc.CallOption) (*FetchLikesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchLikesResp)
	err := c.cc.Invoke(ctx, Driftnode_FetchLikes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driftnodeClient) Profile(ctx context.Context, in *ProfileReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResp)
	err := c.cc.Invoke(ctx, Driftnode_Profile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driftnodeClient) Detail(ctx context.Context, in *DetailReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResp)
	err := c.cc.Invoke(ctx, Driftnode_Detail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driftnodeClient) Zens(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ZensResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ZensResp)
	err := c.cc.Invoke(ctx, Driftnode_Zens_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driftnodeClient) Verify(ctx context.Context, in *IdentityReq, opts ...grpc.CallOption) (*VerifyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyResp)
	err := c.cc.Invoke(ctx, Driftnode_Verify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driftnodeClient) Unverify(ctx context.Context, in *IdentityReq, opts ...grpc.CallOption) (*VerifyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyResp)
	err := c.cc.Invoke(ctx, Driftnode_Unverify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driftnodeClient) Follow(ctx context.Context, in *FollowReq, opts ...grpc.CallOption) (*FollowResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FollowResp)
	err := c.cc.Invoke(ctx, Driftnode_Follow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driftnodeClient) Unfollow(ctx context.Context, in *UnfollowReq, opts ...grpc.CallOption) (*UnfollowResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnfollowResp)
	err := c.cc.Invoke(ctx, Driftnode_Unfollow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driftnodeClient) Unlock(ctx context.Context, in *UnlockReq, opts ...grpc.CallOption) (*UnlockResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnlockResp)
	err := c.cc.Invoke(ctx, Driftnode_Unlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driftnodeClient) Lock(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*EmptyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResp)
	err := c.cc.Invoke(ctx, Driftnode_Lock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driftnodeClient) Sync(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*EmptyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResp)
	err := c.cc.Invoke(ctx, Driftnode_Sync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driftnodeClient) Stop(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*EmptyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResp)
	err := c.cc.Invoke(ctx, Driftnode_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driftnodeClient) Status(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResp)
	err := c.cc.Invoke(ctx, Driftnode_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driftnodeClient) RotateKey(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RotateKeyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RotateKeyResp)
	err := c.cc.Invoke(ctx, Driftnode_RotateKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driftnodeClient) Subscribe(ctx context.Context, in *SubscribeReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Driftnode_ServiceDesc.Streams[0], Driftnode_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeReq, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Driftnode_SubscribeClient = grpc.ServerStreamingClient[Event]

func (c *driftnodeClient) FeedPage(ctx context.Context, in *FeedPageReq, opts ...grpc.CallOption) (*FeedPageResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FeedPageResp)
	err := c.cc.Invoke(ctx, Driftnode_FeedPage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DriftnodeServer is the server API for Driftnode service.
// All implementations must embed UnimplementedDriftnodeServer
// for forward compatibility.
//
// Driftnode is the control-plane API the daemon exposes to the CLI and TUI
// over a Unix domain socket. Unary RPCs cover one-shot commands; Subscribe is
// a server stream of typed events that replaces the old polling model.
type DriftnodeServer interface {
	Whoami(context.Context, *Empty) (*WhoamiResp, error)
	Follows(context.Context, *Empty) (*IdentitiesResp, error)
	Followers(context.Context, *Empty) (*IdentitiesResp, error)
	Post(context.Context, *PostReq) (*PostResp, error)
	Like(context.Context, *LikeReq) (*LikeResp, error)
	FetchLikes(context.Context, *FetchLikesReq) (*FetchLikesResp, error)
	Profile(context.Context, *ProfileReq) (*EmptyResp, error)
	Detail(context.Context, *DetailReq) (*EmptyResp, error)
	Zens(context.Context, *Empty) (*ZensResp, error)
	Verify(context.Context, *IdentityReq) (*VerifyResp, error)
	Unverify(context.Context, *IdentityReq) (*VerifyResp, error)
	Follow(context.Context, *FollowReq) (*FollowResp, error)
	Unfollow(context.Context, *UnfollowReq) (*UnfollowResp, error)
	Unlock(context.Context, *UnlockReq) (*UnlockResp, error)
	Lock(context.Context, *Empty) (*EmptyResp, error)
	Sync(context.Context, *Empty) (*EmptyResp, error)
	Stop(context.Context, *Empty) (*EmptyResp, error)
	Status(context.Context, *Empty) (*StatusResp, error)
	RotateKey(context.Context, *Empty) (*RotateKeyResp, error)
	Subscribe(*SubscribeReq, grpc.ServerStreamingServer[Event]) error
	FeedPage(context.Context, *FeedPageReq) (*FeedPageResp, error)
	mustEmbedUnimplementedDriftnodeServer()
}

// UnimplementedDriftnodeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDriftnodeServer struct{}

func (UnimplementedDriftnodeServer) Whoami(context.Context, *Empty) (*WhoamiResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Whoami not implemented")
}
func (UnimplementedDriftnodeServer) Follows(context.Context, *Empty) (*IdentitiesResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Follows not implemented")
}
func (UnimplementedDriftnodeServer) Followers(context.Context, *Empty) (*IdentitiesResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Followers not implemented")
}
func (UnimplementedDriftnodeServer) Post(context.Context, *PostReq) (*PostResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Post not implemented")
}
func (UnimplementedDriftnodeServer) Like(context.Context, *LikeReq) (*LikeResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Like not implemented")
}
func (UnimplementedDriftnodeServer) FetchLikes(context.Context, *FetchLikesReq) (*FetchLikesResp, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchLikes not implemented")
}
func (UnimplementedDriftnodeServer) Profile(context.Context, *ProfileReq) (*EmptyResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Profile not implemented")
}
func (UnimplementedDriftnodeServer) Detail(context.Context, *DetailReq) (*EmptyResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Detail not implemented")
}
func (UnimplementedDriftnodeServer) Zens(context.Context, *Empty) (*ZensResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Zens not implemented")
}
func (UnimplementedDriftnodeServer) Verify(context.Context, *IdentityReq) (*VerifyResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Verify not implemented")
}
func (UnimplementedDriftnodeServer) Unverify(context.Context, *IdentityReq) (*VerifyResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Unverify not implemented")
}
func (UnimplementedDriftnodeServer) Follow(context.Context, *FollowReq) (*FollowResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Follow not implemented")
}
func (UnimplementedDriftnodeServer) Unfollow(context.Context, *UnfollowReq) (*UnfollowResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Unfollow not implemented")
}
func (UnimplementedDriftnodeServer) Unlock(context.Context, *UnlockReq) (*UnlockResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Unlock not implemented")
}
func (UnimplementedDriftnodeServer) Lock(context.Context, *Empty) (*EmptyResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Lock not implemented")
}
func (UnimplementedDriftnodeServer) Sync(context.Context, *Empty) (*EmptyResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Sync not implemented")
}
func (UnimplementedDriftnodeServer) Stop(context.Context, *Empty) (*EmptyResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedDriftnodeServer) Status(context.Context, *Empty) (*StatusResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedDriftnodeServer) RotateKey(context.Context, *Empty) (*RotateKeyResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RotateKey not implemented")
}
func (UnimplementedDriftnodeServer) Subscribe(*SubscribeReq, grpc.ServerStreamingServer[Event]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedDriftnodeServer) FeedPage(context.Context, *FeedPageReq) (*FeedPageResp, error) {
	return nil, status.Error(codes.Unimplemented, "method FeedPage not implemented")
}
func (UnimplementedDriftnodeServer) mustEmbedUnimplementedDriftnodeServer() {}
func (UnimplementedDriftnodeServer) testEmbeddedByValue()                   {}

// UnsafeDriftnodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DriftnodeServer will
// result in compilation errors.
type UnsafeDriftnodeServer interface {
	mustEmbedUnimplementedDriftnodeServer()
}

func RegisterDriftnodeServer(s grpc.ServiceRegistrar, srv DriftnodeServer) {
	// If the following call panics, it indicates UnimplementedDriftnodeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Driftnode_ServiceDesc, srv)
}

func _Driftnode_Whoami_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriftnodeServer).Whoami(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driftnode_Whoami_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriftnodeServer).Whoami(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driftnode_Follows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriftnodeServer).Follows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driftnode_Follows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriftnodeServer).Follows(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driftnode_Followers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriftnodeServer).Followers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driftnode_Followers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriftnodeServer).Followers(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driftnode_Post_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriftnodeServer).Post(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driftnode_Post_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriftnodeServer).Post(ctx, req.(*PostReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driftnode_Like_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriftnodeServer).Like(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driftnode_Like_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriftnodeServer).Like(ctx, req.(*LikeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driftnode_FetchLikes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchLikesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriftnodeServer).FetchLikes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driftnode_FetchLikes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriftnodeServer).FetchLikes(ctx, req.(*FetchLikesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driftnode_Profile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriftnodeServer).Profile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driftnode_Profile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriftnodeServer).Profile(ctx, req.(*ProfileReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driftnode_Detail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriftnodeServer).Detail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driftnode_Detail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriftnodeServer).Detail(ctx, req.(*DetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driftnode_Zens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriftnodeServer).Zens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driftnode_Zens_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriftnodeServer).Zens(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driftnode_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdentityReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriftnodeServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driftnode_Verify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriftnodeServer).Verify(ctx, req.(*IdentityReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driftnode_Unverify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdentityReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriftnodeServer).Unverify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driftnode_Unverify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriftnodeServer).Unverify(ctx, req.(*IdentityReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driftnode_Follow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriftnodeServer).Follow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driftnode_Follow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriftnodeServer).Follow(ctx, req.(*FollowReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driftnode_Unfollow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnfollowReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriftnodeServer).Unfollow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driftnode_Unfollow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriftnodeServer).Unfollow(ctx, req.(*UnfollowReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driftnode_Unlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlockReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriftnodeServer).Unlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driftnode_Unlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriftnodeServer).Unlock(ctx, req.(*UnlockReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driftnode_Lock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriftnodeServer).Lock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driftnode_Lock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriftnodeServer).Lock(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driftnode_Sync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriftnodeServer).Sync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driftnode_Sync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriftnodeServer).Sync(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driftnode_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriftnodeServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driftnode_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriftnodeServer).Stop(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driftnode_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriftnodeServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driftnode_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriftnodeServer).Status(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driftnode_RotateKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriftnodeServer).RotateKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driftnode_RotateKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriftnodeServer).RotateKey(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driftnode_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DriftnodeServer).Subscribe(m, &grpc.GenericServerStream[SubscribeReq, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Driftnode_SubscribeServer = grpc.ServerStreamingServer[Event]

func _Driftnode_FeedPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeedPageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriftnodeServer).FeedPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driftnode_FeedPage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriftnodeServer).FeedPage(ctx, req.(*FeedPageReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Driftnode_ServiceDesc is the grpc.ServiceDesc for Driftnode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Driftnode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "driftnode.v1.Driftnode",
	HandlerType: (*DriftnodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Whoami",
			Handler:    _Driftnode_Whoami_Handler,
		},
		{
			MethodName: "Follows",
			Handler:    _Driftnode_Follows_Handler,
		},
		{
			MethodName: "Followers",
			Handler:    _Driftnode_Followers_Handler,
		},
		{
			MethodName: "Post",
			Handler:    _Driftnode_Post_Handler,
		},
		{
			MethodName: "Like",
			Handler:    _Driftnode_Like_Handler,
		},
		{
			MethodName: "FetchLikes",
			Handler:    _Driftnode_FetchLikes_Handler,
		},
		{
			MethodName: "Profile",
			Handler:    _Driftnode_Profile_Handler,
		},
		{
			MethodName: "Detail",
			Handler:    _Driftnode_Detail_Handler,
		},
		{
			MethodName: "Zens",
			Handler:    _Driftnode_Zens_Handler,
		},
		{
			MethodName: "Verify",
			Handler:    _Driftnode_Verify_Handler,
		},
		{
			MethodName: "Unverify",
			Handler:    _Driftnode_Unverify_Handler,
		},
		{
			MethodName: "Follow",
			Handler:    _Driftnode_Follow_Handler,
		},
		{
			MethodName: "Unfollow",
			Handler:    _Driftnode_Unfollow_Handler,
		},
		{
			MethodName: "Unlock",
			Handler:    _Driftnode_Unlock_Handler,
		},
		{
			MethodName: "Lock",
			Handler:    _Driftnode_Lock_Handler,
		},
		{
			MethodName: "Sync",
			Handler:    _Driftnode_Sync_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _Driftnode_Stop_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _Driftnode_Status_Handler,
		},
		{
			MethodName: "RotateKey",
			Handler:    _Driftnode_RotateKey_Handler,
		},
		{
			MethodName: "FeedPage",
			Handler:    _Driftnode_FeedPage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _Driftnode_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "driftnode.proto",
}
